#! /bin/sh


export RBW_PROFILE="$1"
#Profile settings saved in ~/.config/rbw-<profilename>


menu="kickoff --from-stdin --stdout -p "$1\>\>" "
#menu="bemenu -b -l 15 -p "$1" --tf "#f25805" --hf "#ff0000" --bdr "#ff0000" --nf "#f25805" --af "#f25805" -B 5 -M 2 "

rbw unlock   
    if [ $? = 1 ]; then
	    exit
    fi

selection1=$( ( printf "View/Type Individual Entries\nOTP Code\nGenerate Password\nSync Vault\nLock Vault\n---------\n" && rbw ls ) | $menu )

case $selection1 in
     "View/Type Individual Entries" )
         selection2=$( rbw ls | $menu )
         selectionfull=$( rbw get "$selection2" --full |  sed '1 s/^.*$/Password: ******/' | $menu )
           if [ "$selectionfull" =   "Password: ******"  ];
           then
             wtype $( rbw get "$selection2" )
           else
            selectiontype=$( printf "$selectionfull" | sed 's/.*: //' )
            wtype $selectiontype
           fi
           ;;

     "OTP Code" )
           wtype "$( rbw code "$(rbw ls | $menu)" )"
           ;;

     "Generate Password" )
           wl-copy "$(rbw generate  20)"
           ;;
    
     "Sync Vault" )
           rbw sync
           ;;
    
     "Lock Vault" )
           rbw lock
           ;;
     * )
           wtype $( rbw get "$selection1" --full | grep Username: | sed 's/Username: //') -k tab $( rbw get "$selection1" ) -k return
           ;;
esac
